services:
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: IdentityServer/IdentityService/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    

volumes:
    mssql_data:
 