services:
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: IdentityServer/IdentityService/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  db.api:
    image: ${DOCKER_REGISTRY-}dbapi
    build:
      context: .
      dockerfile: Services/DB/DB.API/DB.API/Dockerfile

  autocomplete.api:
    image: ${DOCKER_REGISTRY-}autocompleteapi
    build:
      context: ..
      dockerfile: Autocomplete.API/Dockerfile

volumes:
  mssql_data:
  autocomplete_data:
