services:
  identityservice:
    container_name: identityservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on: 
      - mssql
    ports:
      - "4000:8080"
  mssql:
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
     #NAPRAVITI ENVIRONMENT PROMENLJIVU ZA PASS
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
    volumes:
      - mssql_data:/var/opt/mssql/data
