### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  commentId: N:DB.Application.Features.Keywords.Queries.GetListOfKeywords
  id: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  children:
  - DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQuery
  - DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQueryHandler
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  nameWithType: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  fullName: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQuery
  commentId: T:DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQuery
  parent: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  href: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQuery.html
  name: GetListOfKeywordsQuery
  nameWithType: GetListOfKeywordsQuery
  fullName: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQuery
- uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQueryHandler
  commentId: T:DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQueryHandler
  href: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQueryHandler.html
  name: GetListOfKeywordsQueryHandler
  nameWithType: GetListOfKeywordsQueryHandler
  fullName: DB.Application.Features.Keywords.Queries.GetListOfKeywords.GetListOfKeywordsQueryHandler
- uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  commentId: N:DB.Application.Features.Keywords.Queries.GetListOfKeywords
  href: DB.html
  name: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  nameWithType: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  fullName: DB.Application.Features.Keywords.Queries.GetListOfKeywords
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Keywords
    name: Keywords
    href: DB.Application.Features.Keywords.html
  - name: .
  - uid: DB.Application.Features.Keywords.Queries
    name: Queries
    href: DB.Application.Features.Keywords.Queries.html
  - name: .
  - uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords
    name: GetListOfKeywords
    href: DB.Application.Features.Keywords.Queries.GetListOfKeywords.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Keywords
    name: Keywords
    href: DB.Application.Features.Keywords.html
  - name: .
  - uid: DB.Application.Features.Keywords.Queries
    name: Queries
    href: DB.Application.Features.Keywords.Queries.html
  - name: .
  - uid: DB.Application.Features.Keywords.Queries.GetListOfKeywords
    name: GetListOfKeywords
    href: DB.Application.Features.Keywords.Queries.GetListOfKeywords.html
