### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  commentId: N:DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  id: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  children:
  - DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQuery
  - DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQueryHandler
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  nameWithType: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQuery
  commentId: T:DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQuery
  parent: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQuery.html
  name: GetAnalysisByMicroorganismQuery
  nameWithType: GetAnalysisByMicroorganismQuery
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQuery
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQueryHandler
  commentId: T:DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQueryHandler
  href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQueryHandler.html
  name: GetAnalysisByMicroorganismQueryHandler
  nameWithType: GetAnalysisByMicroorganismQueryHandler
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.GetAnalysisByMicroorganismQueryHandler
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  commentId: N:DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  nameWithType: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
    name: GetMicroorganismWithAnalyses
    href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses
    name: GetMicroorganismWithAnalyses
    href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithAnalyses.html
