### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery
  commentId: T:DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery
  id: GetListOfInstrumentsQuery
  parent: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  children:
  - DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor(System.String)
  - DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
  langs:
  - csharp
  - vb
  name: GetListOfInstrumentsQuery
  nameWithType: GetListOfInstrumentsQuery
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery
  type: Class
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: GetListOfInstrumentsQuery
    path: ../SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
    startLine: 10
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  syntax:
    content: 'public class GetListOfInstrumentsQuery : IRequest<IReadOnlyCollection<InstrumentViewModel>>, IBaseRequest'
    content.vb: Public Class GetListOfInstrumentsQuery Implements IRequest(Of IReadOnlyCollection(Of InstrumentViewModel)), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{System.Collections.Generic.IReadOnlyCollection{DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel}}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
  commentId: P:DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
  id: Name
  parent: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: GetListOfInstrumentsQuery.Name
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
  type: Property
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: Name
    path: ../SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
    startLine: 12
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name*
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor(System.String)
  commentId: M:DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery
  langs:
  - csharp
  - vb
  name: GetListOfInstrumentsQuery(string)
  nameWithType: GetListOfInstrumentsQuery.GetListOfInstrumentsQuery(string)
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.GetListOfInstrumentsQuery(string)
  type: Constructor
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: .ctor
    path: ../SciConnect/Services/DB/DB.Application/Features/Instruments/Queries/GetListOfInstruments/GetListOfInstrumentsQuery.cs
    startLine: 14
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  syntax:
    content: public GetListOfInstrumentsQuery(string name)
    parameters:
    - id: name
      type: System.String
    content.vb: Public Sub New(name As String)
  overload: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor*
  nameWithType.vb: GetListOfInstrumentsQuery.New(String)
  fullName.vb: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.New(String)
  name.vb: New(String)
references:
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  commentId: N:DB.Application.Features.Instruments.Queries.GetListOfInstruments
  href: DB.html
  name: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  nameWithType: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Instruments
    name: Instruments
    href: DB.Application.Features.Instruments.html
  - name: .
  - uid: DB.Application.Features.Instruments.Queries
    name: Queries
    href: DB.Application.Features.Instruments.Queries.html
  - name: .
  - uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments
    name: GetListOfInstruments
    href: DB.Application.Features.Instruments.Queries.GetListOfInstruments.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Instruments
    name: Instruments
    href: DB.Application.Features.Instruments.html
  - name: .
  - uid: DB.Application.Features.Instruments.Queries
    name: Queries
    href: DB.Application.Features.Instruments.Queries.html
  - name: .
  - uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments
    name: GetListOfInstruments
    href: DB.Application.Features.Instruments.Queries.GetListOfInstruments.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{System.Collections.Generic.IReadOnlyCollection{DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel}}
  commentId: T:MediatR.IRequest{System.Collections.Generic.IReadOnlyCollection{DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel}}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlycollection-1
  name: IRequest<IReadOnlyCollection<InstrumentViewModel>>
  nameWithType: IRequest<IReadOnlyCollection<InstrumentViewModel>>
  fullName: MediatR.IRequest<System.Collections.Generic.IReadOnlyCollection<DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel>>
  nameWithType.vb: IRequest(Of IReadOnlyCollection(Of InstrumentViewModel))
  fullName.vb: MediatR.IRequest(Of System.Collections.Generic.IReadOnlyCollection(Of DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel))
  name.vb: IRequest(Of IReadOnlyCollection(Of InstrumentViewModel))
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: System.Collections.Generic.IReadOnlyCollection`1
    name: IReadOnlyCollection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlycollection-1
  - name: <
  - uid: DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel
    name: InstrumentViewModel
    href: DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel.html
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Collections.Generic.IReadOnlyCollection`1
    name: IReadOnlyCollection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlycollection-1
  - name: (
  - name: Of
  - name: " "
  - uid: DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel
    name: InstrumentViewModel
    href: DB.Application.Features.Instruments.Queries.ViewModels.InstrumentViewModel.html
  - name: )
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name*
  commentId: Overload:DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
  href: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.html#DB_Application_Features_Instruments_Queries_GetListOfInstruments_GetListOfInstrumentsQuery_Name
  name: Name
  nameWithType: GetListOfInstrumentsQuery.Name
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor*
  commentId: Overload:DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.#ctor
  href: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.html#DB_Application_Features_Instruments_Queries_GetListOfInstruments_GetListOfInstrumentsQuery__ctor_System_String_
  name: GetListOfInstrumentsQuery
  nameWithType: GetListOfInstrumentsQuery.GetListOfInstrumentsQuery
  fullName: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.GetListOfInstrumentsQuery
  nameWithType.vb: GetListOfInstrumentsQuery.New
  fullName.vb: DB.Application.Features.Instruments.Queries.GetListOfInstruments.GetListOfInstrumentsQuery.New
  name.vb: New
