### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  commentId: N:DB.Application.Features.Analyses.Commands.DeleteAnalysis
  id: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  children:
  - DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommand
  - DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommandHandler
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  nameWithType: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  fullName: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommand
  commentId: T:DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommand
  parent: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  href: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommand.html
  name: DeleteAnalysisCommand
  nameWithType: DeleteAnalysisCommand
  fullName: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommand
- uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommandHandler
  commentId: T:DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommandHandler
  href: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommandHandler.html
  name: DeleteAnalysisCommandHandler
  nameWithType: DeleteAnalysisCommandHandler
  fullName: DB.Application.Features.Analyses.Commands.DeleteAnalysis.DeleteAnalysisCommandHandler
- uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  commentId: N:DB.Application.Features.Analyses.Commands.DeleteAnalysis
  href: DB.html
  name: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  nameWithType: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  fullName: DB.Application.Features.Analyses.Commands.DeleteAnalysis
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analyses
    name: Analyses
    href: DB.Application.Features.Analyses.html
  - name: .
  - uid: DB.Application.Features.Analyses.Commands
    name: Commands
    href: DB.Application.Features.Analyses.Commands.html
  - name: .
  - uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis
    name: DeleteAnalysis
    href: DB.Application.Features.Analyses.Commands.DeleteAnalysis.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analyses
    name: Analyses
    href: DB.Application.Features.Analyses.html
  - name: .
  - uid: DB.Application.Features.Analyses.Commands
    name: Commands
    href: DB.Application.Features.Analyses.Commands.html
  - name: .
  - uid: DB.Application.Features.Analyses.Commands.DeleteAnalysis
    name: DeleteAnalysis
    href: DB.Application.Features.Analyses.Commands.DeleteAnalysis.html
