### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  commentId: N:DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  id: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  children:
  - DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQuery
  - DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQueryHandler
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  nameWithType: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQuery
  commentId: T:DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQuery
  parent: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  href: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQuery.html
  name: GetInstitutionsByAnalysisQuery
  nameWithType: GetInstitutionsByAnalysisQuery
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQuery
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQueryHandler
  commentId: T:DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQueryHandler
  href: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQueryHandler.html
  name: GetInstitutionsByAnalysisQueryHandler
  nameWithType: GetInstitutionsByAnalysisQueryHandler
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.GetInstitutionsByAnalysisQueryHandler
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  commentId: N:DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  nameWithType: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
    name: GetAnalysisWithInstitution
    href: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution
    name: GetAnalysisWithInstitution
    href: DB.Application.Features.Analysis.Queries.GetAnalysisWithInstitution.html
