### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery
  commentId: T:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery
  id: GetInstitutionByMicroorganismQuery
  parent: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  children:
  - DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor(System.String)
  - DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
  langs:
  - csharp
  - vb
  name: GetInstitutionByMicroorganismQuery
  nameWithType: GetInstitutionByMicroorganismQuery
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery
  type: Class
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: GetInstitutionByMicroorganismQuery
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
    startLine: 10
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  syntax:
    content: 'public class GetInstitutionByMicroorganismQuery : IRequest<MicroorganismViewModel>, IBaseRequest'
    content.vb: Public Class GetInstitutionByMicroorganismQuery Implements IRequest(Of MicroorganismViewModel), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
  commentId: P:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
  id: MicroorganismName
  parent: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery
  langs:
  - csharp
  - vb
  name: MicroorganismName
  nameWithType: GetInstitutionByMicroorganismQuery.MicroorganismName
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
  type: Property
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: MicroorganismName
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
    startLine: 12
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  syntax:
    content: public string MicroorganismName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property MicroorganismName As String
  overload: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName*
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor(System.String)
  commentId: M:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery
  langs:
  - csharp
  - vb
  name: GetInstitutionByMicroorganismQuery(string)
  nameWithType: GetInstitutionByMicroorganismQuery.GetInstitutionByMicroorganismQuery(string)
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.GetInstitutionByMicroorganismQuery(string)
  type: Constructor
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: .ctor
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Queries/GetMicroorganismWithInstitutions/GetInstitutionByMicroorganismQuery.cs
    startLine: 14
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  syntax:
    content: public GetInstitutionByMicroorganismQuery(string microorganismName)
    parameters:
    - id: microorganismName
      type: System.String
    content.vb: Public Sub New(microorganismName As String)
  overload: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor*
  nameWithType.vb: GetInstitutionByMicroorganismQuery.New(String)
  fullName.vb: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.New(String)
  name.vb: New(String)
references:
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  commentId: N:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  nameWithType: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
    name: GetMicroorganismWithInstitutions
    href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions
    name: GetMicroorganismWithInstitutions
    href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel}
  commentId: T:MediatR.IRequest{DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel.html
  name: IRequest<MicroorganismViewModel>
  nameWithType: IRequest<MicroorganismViewModel>
  fullName: MediatR.IRequest<DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel>
  nameWithType.vb: IRequest(Of MicroorganismViewModel)
  fullName.vb: MediatR.IRequest(Of DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel)
  name.vb: IRequest(Of MicroorganismViewModel)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel
    name: MicroorganismViewModel
    href: DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel.html
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel
    name: MicroorganismViewModel
    href: DB.Application.Features.Microorganisms.Queries.ViewModels.MicroorganismViewModel.html
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName*
  commentId: Overload:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
  href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.html#DB_Application_Features_Analysis_Queries_GetMicroorganismWithInstitutions_GetInstitutionByMicroorganismQuery_MicroorganismName
  name: MicroorganismName
  nameWithType: GetInstitutionByMicroorganismQuery.MicroorganismName
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.MicroorganismName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor*
  commentId: Overload:DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.#ctor
  href: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.html#DB_Application_Features_Analysis_Queries_GetMicroorganismWithInstitutions_GetInstitutionByMicroorganismQuery__ctor_System_String_
  name: GetInstitutionByMicroorganismQuery
  nameWithType: GetInstitutionByMicroorganismQuery.GetInstitutionByMicroorganismQuery
  fullName: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.GetInstitutionByMicroorganismQuery
  nameWithType.vb: GetInstitutionByMicroorganismQuery.New
  fullName.vb: DB.Application.Features.Analysis.Queries.GetMicroorganismWithInstitutions.GetInstitutionByMicroorganismQuery.New
  name.vb: New
