### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  commentId: N:DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  id: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  children:
  - DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQuery
  - DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQueryHandler
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  nameWithType: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  fullName: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQuery
  commentId: T:DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQuery
  parent: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  href: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQuery.html
  name: GetListOfAnalysisQuery
  nameWithType: GetListOfAnalysisQuery
  fullName: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQuery
- uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQueryHandler
  commentId: T:DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQueryHandler
  href: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQueryHandler.html
  name: GetListOfAnalysisQueryHandler
  nameWithType: GetListOfAnalysisQueryHandler
  fullName: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.GetListOfAnalysisQueryHandler
- uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  commentId: N:DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  nameWithType: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  fullName: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
    name: GetListOfAnalysis
    href: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetListOfAnalysis
    name: GetListOfAnalysis
    href: DB.Application.Features.Analysis.Queries.GetListOfAnalysis.html
