### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand
  commentId: T:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand
  id: CreateMicroorganismCommand
  parent: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  children:
  - DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor(System.String)
  - DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
  langs:
  - csharp
  - vb
  name: CreateMicroorganismCommand
  nameWithType: CreateMicroorganismCommand
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand
  type: Class
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: CreateMicroorganismCommand
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
    startLine: 10
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  syntax:
    content: 'public class CreateMicroorganismCommand : IRequest<int>, IBaseRequest'
    content.vb: Public Class CreateMicroorganismCommand Implements IRequest(Of Integer), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{System.Int32}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
  commentId: P:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
  id: Name
  parent: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CreateMicroorganismCommand.Name
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
  type: Property
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: Name
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
    startLine: 12
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name*
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor(System.String)
  commentId: M:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand
  langs:
  - csharp
  - vb
  name: CreateMicroorganismCommand(string)
  nameWithType: CreateMicroorganismCommand.CreateMicroorganismCommand(string)
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.CreateMicroorganismCommand(string)
  type: Constructor
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: .ctor
    path: ../SciConnect/Services/DB/DB.Application/Features/Microorganisms/Commands/CreateMicroorganism/CreateMicroorganismCommand.cs
    startLine: 16
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  syntax:
    content: public CreateMicroorganismCommand(string name)
    parameters:
    - id: name
      type: System.String
    content.vb: Public Sub New(name As String)
  overload: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor*
  nameWithType.vb: CreateMicroorganismCommand.New(String)
  fullName.vb: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.New(String)
  name.vb: New(String)
references:
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  commentId: N:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  href: DB.html
  name: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  nameWithType: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Microorganisms
    name: Microorganisms
    href: DB.Application.Features.Microorganisms.html
  - name: .
  - uid: DB.Application.Features.Microorganisms.Commands
    name: Commands
    href: DB.Application.Features.Microorganisms.Commands.html
  - name: .
  - uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
    name: CreateMicroorganism
    href: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Microorganisms
    name: Microorganisms
    href: DB.Application.Features.Microorganisms.html
  - name: .
  - uid: DB.Application.Features.Microorganisms.Commands
    name: Commands
    href: DB.Application.Features.Microorganisms.Commands.html
  - name: .
  - uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism
    name: CreateMicroorganism
    href: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{System.Int32}
  commentId: T:MediatR.IRequest{System.Int32}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: IRequest<int>
  nameWithType: IRequest<int>
  fullName: MediatR.IRequest<int>
  nameWithType.vb: IRequest(Of Integer)
  fullName.vb: MediatR.IRequest(Of Integer)
  name.vb: IRequest(Of Integer)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name*
  commentId: Overload:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
  href: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.html#DB_Application_Features_Microorganisms_Commands_CreateMicroorganism_CreateMicroorganismCommand_Name
  name: Name
  nameWithType: CreateMicroorganismCommand.Name
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor*
  commentId: Overload:DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.#ctor
  href: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.html#DB_Application_Features_Microorganisms_Commands_CreateMicroorganism_CreateMicroorganismCommand__ctor_System_String_
  name: CreateMicroorganismCommand
  nameWithType: CreateMicroorganismCommand.CreateMicroorganismCommand
  fullName: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.CreateMicroorganismCommand
  nameWithType.vb: CreateMicroorganismCommand.New
  fullName.vb: DB.Application.Features.Microorganisms.Commands.CreateMicroorganism.CreateMicroorganismCommand.New
  name.vb: New
