### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.ViewModels
  commentId: N:DB.Application.Features.Analysis.Queries.ViewModels
  id: DB.Application.Features.Analysis.Queries.ViewModels
  children:
  - DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
  langs:
  - csharp
  - vb
  name: DB.Application.Features.Analysis.Queries.ViewModels
  nameWithType: DB.Application.Features.Analysis.Queries.ViewModels
  fullName: DB.Application.Features.Analysis.Queries.ViewModels
  type: Namespace
  assemblies:
  - DB.Application
references:
- uid: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
  commentId: T:DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
  parent: DB.Application.Features.Analysis.Queries.ViewModels
  href: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel.html
  name: AnalysisViewModel
  nameWithType: AnalysisViewModel
  fullName: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
- uid: DB.Application.Features.Analysis.Queries.ViewModels
  commentId: N:DB.Application.Features.Analysis.Queries.ViewModels
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.ViewModels
  nameWithType: DB.Application.Features.Analysis.Queries.ViewModels
  fullName: DB.Application.Features.Analysis.Queries.ViewModels
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.ViewModels
    name: ViewModels
    href: DB.Application.Features.Analysis.Queries.ViewModels.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.ViewModels
    name: ViewModels
    href: DB.Application.Features.Analysis.Queries.ViewModels.html
