### YamlMime:ManagedReference
items:
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery
  commentId: T:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery
  id: GetMicroorganismsByAnalysisQuery
  parent: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  children:
  - DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor(System.String)
  - DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
  langs:
  - csharp
  - vb
  name: GetMicroorganismsByAnalysisQuery
  nameWithType: GetMicroorganismsByAnalysisQuery
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery
  type: Class
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: GetMicroorganismsByAnalysisQuery
    path: ../SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
    startLine: 10
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  syntax:
    content: 'public class GetMicroorganismsByAnalysisQuery : IRequest<AnalysisViewModel>, IBaseRequest'
    content.vb: Public Class GetMicroorganismsByAnalysisQuery Implements IRequest(Of AnalysisViewModel), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
  commentId: P:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
  id: AnalysisName
  parent: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery
  langs:
  - csharp
  - vb
  name: AnalysisName
  nameWithType: GetMicroorganismsByAnalysisQuery.AnalysisName
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
  type: Property
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: AnalysisName
    path: ../SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
    startLine: 12
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  syntax:
    content: public string AnalysisName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AnalysisName As String
  overload: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName*
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor(System.String)
  commentId: M:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery
  langs:
  - csharp
  - vb
  name: GetMicroorganismsByAnalysisQuery(string)
  nameWithType: GetMicroorganismsByAnalysisQuery.GetMicroorganismsByAnalysisQuery(string)
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.GetMicroorganismsByAnalysisQuery(string)
  type: Constructor
  source:
    remote:
      path: SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
      branch: feature/autocomplete
      repo: https://github.com/RS2-Crew/SciConnect.git
    id: .ctor
    path: ../SciConnect/Services/DB/DB.Application/Features/Analysis/Queries/GetAnalysisWithMicroorganism/GetMicroorganismsByAnalysisQuery.cs
    startLine: 14
  assemblies:
  - DB.Application
  namespace: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  syntax:
    content: public GetMicroorganismsByAnalysisQuery(string analysisName)
    parameters:
    - id: analysisName
      type: System.String
    content.vb: Public Sub New(analysisName As String)
  overload: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor*
  nameWithType.vb: GetMicroorganismsByAnalysisQuery.New(String)
  fullName.vb: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.New(String)
  name.vb: New(String)
references:
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  commentId: N:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  href: DB.html
  name: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  nameWithType: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
  spec.csharp:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
    name: GetAnalysisWithMicroorganism
    href: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.html
  spec.vb:
  - uid: DB
    name: DB
    href: DB.html
  - name: .
  - uid: DB.Application
    name: Application
    href: DB.Application.html
  - name: .
  - uid: DB.Application.Features
    name: Features
    href: DB.Application.Features.html
  - name: .
  - uid: DB.Application.Features.Analysis
    name: Analysis
    href: DB.Application.Features.Analysis.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries
    name: Queries
    href: DB.Application.Features.Analysis.Queries.html
  - name: .
  - uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism
    name: GetAnalysisWithMicroorganism
    href: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel}
  commentId: T:MediatR.IRequest{DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel.html
  name: IRequest<AnalysisViewModel>
  nameWithType: IRequest<AnalysisViewModel>
  fullName: MediatR.IRequest<DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel>
  nameWithType.vb: IRequest(Of AnalysisViewModel)
  fullName.vb: MediatR.IRequest(Of DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel)
  name.vb: IRequest(Of AnalysisViewModel)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
    name: AnalysisViewModel
    href: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel.html
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel
    name: AnalysisViewModel
    href: DB.Application.Features.Analysis.Queries.ViewModels.AnalysisViewModel.html
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName*
  commentId: Overload:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
  href: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.html#DB_Application_Features_Analysis_Queries_GetAnalysisWithMicroorganism_GetMicroorganismsByAnalysisQuery_AnalysisName
  name: AnalysisName
  nameWithType: GetMicroorganismsByAnalysisQuery.AnalysisName
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.AnalysisName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor*
  commentId: Overload:DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.#ctor
  href: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.html#DB_Application_Features_Analysis_Queries_GetAnalysisWithMicroorganism_GetMicroorganismsByAnalysisQuery__ctor_System_String_
  name: GetMicroorganismsByAnalysisQuery
  nameWithType: GetMicroorganismsByAnalysisQuery.GetMicroorganismsByAnalysisQuery
  fullName: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.GetMicroorganismsByAnalysisQuery
  nameWithType.vb: GetMicroorganismsByAnalysisQuery.New
  fullName.vb: DB.Application.Features.Analysis.Queries.GetAnalysisWithMicroorganism.GetMicroorganismsByAnalysisQuery.New
  name.vb: New
